from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView
from . import views


urlpatterns = [
    path(
        'token/',
        TokenObtainPairView.as_view
            (
                serializer_class=views.CustomTokenObtainPairSerializer
            ),
        name='token_obtain_pair'
    ),
    path(
        'register/',
        views.VenueRegistrationView.as_view(),
        name='register'
    ),
    path(
        'genres/',
        views.GenresView.as_view(),
        name='genres'
    ),
    path(
        'profile/',
         views.VenueView.as_view(),
         name='profile'
    ),
    path(
        'venue/<int:venue_id>/tracks/',
         views.VenueTrackListView.as_view(),
         name='tracks-list'
    ),
    path(
        'venue/<int:venue_id>/tracks/<int:track_id>/',
        views.TrackDetailView.as_view(),
        name='track-detail'
    ),
    path(
        'venue/<int:venue_id>/request/',
         views.TrackRequestCreateView.as_view(),
         name='track-request-create'
    ),
    path(
        'requests/',
         views.TrackRequestListView.as_view(),
         name='track-request-list'
    ),
    path(
        'requests/<int:pk>/',
         views.TrackRequestUpdateView.as_view(),
         name='track-request-update'
    ),
    path(
        'withdrawals/',
        views.WithdrawalView.as_view(),
        name='withdrawal-create'
    ),
    path(
        'requests/pay/<uuid:payment_token>/',
        views.MockPaymentView.as_view(),
        name='mock-payment'
    ),
    path(
        'transactions/',
        views.TransactionListView.as_view(),
        name='transaction-list'
    ),
    path(
        'withdrawals/history/',
        views.WithdrawalListView.as_view(),
        name='withdrawal-history'
    ),
    path(
        'payment/<uuid:payment_token>/',
        views.PaymentCreateView.as_view(),
        name='create-payment'
    ),
    path(
        'payment-webhook/',
        views.PaymentWebhookView.as_view(),
        name='payment-webhook'
    ),
    path(
        'withdrawal-webhook/',
        views.WithdrawalWebhookView.as_view(),
        name='withdrawal-webhook'
    ),
    path(
        'mock-withdraw/',
        views.MockWithdrawalView.as_view(),
        name='mock-withdrawal'
    ),
]
